const express = require("express")
const app = express()
const cors = require("cors")
const dotenv = require("dotenv")
const helmet = require("helmet")
const connectDB = require("../src/config/dbConnect")
const userRoute = require("../src/user/userRoute")
dotenv.config()

app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(helmet())
app.use("/api/v1/", userRoute)
connectDB()
app.listen(process.env.PORT, () => {
    console.log(`Server is running on port ${process.env.PORT}`)
})